baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New  Site'

theme = "pehtheme-hugo"

[pagination]
  pagerSize = 6

[params]
  summaryLength = 20
  googleAnalytics = ''  # Add your GA4 code
  disqusShortname = ''  # Add your Disqus shortname