baseURL: "https://odai357.github.io/pehtheme/"
languageCode: "en-us"
title: "Odai-泽鑫 - Profile"
theme: hugo-profile
relativeURLs: true
canonifyURLs: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

services:
  googleAnalytics:
    id: G-GG0WJKJVBF
  #disqus:
    #shortname: your-disqus-shortname

privacy:
  googleAnalytics:
    disable: false
    respectDoNotTrack: false

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/con1.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "HOPE" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Odai-泽鑫"
    subtitle: "I bridge Earth's coordinates with universal potential"
    content: "🌟温故知新🌟"
    image: /images/hero1.png
    bottomImage:
      enable: true
      roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/odai357
        - icon: fab fa-x-twitter
          url: https://x.com/OdaiRma357
      customIcons:
        - icon: /images/con1.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a postgraduate researcher at BUAA's RCSSTEAP, specializing in GNSS and hybrid indoor/outdoor navigation systems. Building on my background in Communication Engineering and multilingual business development, I now focus on solving challenging positioning problems in complex environments.

      
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
       - "GNSS Positioning Algorithms"
       - "Sensor Fusion for Navigation"
       - "Indoor Positioning Systems"
       - "MATLAB/Python for Engineering"
       - "Satellite Navigation Data Analysis"
       - "Multilingual Technical Communication"
       - "Research Collaboration"
       - "SSR/BDS Systems"



  # Assignments
  projects:
    enable: true
    title: "Assignments"
    items:
      - title: Assignment 1
        content: Matrix Multiplication Project Report
        image: /images/brent-cox-ydGRmobx5jA-unsplash.jpg
        featured:
          name: "View"
          link: /posts/1/assignment-1/
        badges:
          - "Markdown"
          - "Python"
          - "C++"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/odai357
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Assignment 2
        content: Static Personal Blog Website Documentation
        image: /images/javardh.jpg
        featured:
          name: "View"
          link: /posts/1/assignment-2/
        badges:
          - "HUGO"
          - "hugo-Profile" 
        links:
          - icon: fab fa-github
            url: https://github.com/odai357

      - title: Assignment 3
        content: Deployment and Integration of LLM
        image: /images/nasa-rh.jpg
        featured:
          name: "View"
          link: /posts/1/assignment-3/
        badges:
          - "Ollama"
          - "Deepseek"
          - "AnythingLLM"
        links:
          - icon: fab fa-github
            url: https://github.com/odai357

      - title: Assignment 4
        content: AI-Assisted Collision Avoidance System
        image: /images/llm.jpg
        featured:
          name: "View"
          link: /posts/1/assignment-4/
        badges:
          - "RGB"
          - "CAS"
          - "EXE"
        links:
          - icon: fab fa-github
            url: https://github.com/odai357

            

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:odai7@buaa.edu.cn
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/odai357
      linkedin: https://www.linkedin.com/in/odai-othman-6699a9339/
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  caches:
    images:
      dir: :cacheDir/images

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
