baseURL: "https://odai357.github.io/pehtheme/"
languageCode: "en-us"
title: "Odai-泽鑫 - Profile"
theme: hugo-profile
relativeURLs: true
canonifyURLs: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

services:
  googleAnalytics:
    id: G-GG0WJKJVBF
  #disqus:
    #shortname: your-disqus-shortname

privacy:
  googleAnalytics:
    disable: false
    respectDoNotTrack: false

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true
  
Menus:
  main:
    - identifier: experience
      name: Experience
      title: Experience
      url: /experience
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/con1.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "HOPE" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Odai-泽鑫"
    subtitle: "I bridge Earth's coordinates with universal potential"
    content: "🌟温故知新🌟"
    image: /images/hero1.png
    bottomImage:
      enable: true
      roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/odai357
        - icon: fab fa-x-twitter
          url: https://x.com/OdaiRma357
      customIcons:
        - icon: /images/con1.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a postgraduate researcher at BUAA's RCSSTEAP, specializing in GNSS and hybrid indoor/outdoor navigation systems. Building on my background in Communication Engineering and multilingual business development, I now focus on solving challenging positioning problems in complex environments.

      
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
       - "GNSS Positioning Algorithms"
       - "Sensor Fusion for Navigation"
       - "Indoor Positioning Systems"
       - "MATLAB/Python for Engineering"
       - "Satellite Navigation Data Analysis"
       - "Multilingual Technical Communication"
       - "Research Collaboration"
       - "SSR/BDS Systems"



  # Projects
  projects:
    enable: true
    title: "Projects"
    items:
      - title: Unveiling Spatial Patterns of Aircraft Occurrences in Brazil Through Clustering and Statistical Analysis
        content: I was part of this research project that investigates aircraft incidents in Brazil using statistical analysis and machine learning techniques to uncover spatial patterns and contributing risk factors in aviation safety. Our work focused heavily on cleaning and correcting inconsistent geographic and aircraft data from the national aviation database maintained by CENIPA, then applying clustering methods such as K-Means, Agglomerative clustering, and density-based approaches alongside statistical tests like chi-square and logistic regression. The analysis revealed clear regional patterns tied to air-traffic infrastructure and showed significant relationships between incident characteristics and their geographic distribution, demonstrating how data-driven methods can support better risk assessment and safety planning in Brazil's aviation sector.
        image: /images/Slide1.PNG
        gallery:
          - url: /images/Slide1.PNG
        featured:
          name: "View Paper (Will be available soon...)"
          link: "#"
        badges:
          - "ML - Clustering"

      - title: Custom-Built Autonomous Drone Platform Using Holybro X500 Frame
        content: This project involved building and configuring a fully functional drone based on the X500 frame from Holybro, integrating flight control hardware, sensors, and onboard computing into a stable aerial platform. The work covered mechanical assembly, flight controller configuration, power distribution, firmware setup, and calibration, followed by test flights to validate stability and responsiveness. The project demonstrates hands-on experience with UAV hardware integration, embedded systems, and real-world debugging, forming a foundation for future work in autonomous navigation, computer vision, or aerial robotics applications.
        image: /images/p2_1.png
        gallery:
          - url: /images/p2_1.png
          - url: /images/p2_2.png
          - url: /images/p2_3.jpg
        badges:
          - "Holybro-X500"

      - title: AI-Assisted Collision Avoidance System
        content: This project presents a self-developed AI-assisted collision avoidance system that detects obstacles in real time using depth sensing and computer vision. It uses an Intel RealSense D435i camera to capture 3D spatial data and combines depth analysis with a CNN-based model to improve detection reliability, generating color-coded safety alerts based on distance. Built primarily in Python with libraries such as OpenCV and TensorFlow, the system maintains real-time performance near 30 FPS while supporting modular components, dataset generation, and deployment on lightweight hardware including Raspberry Pi. AI development tools like GitHub Copilot and ChatGPT were used to accelerate experimentation, optimization, and debugging, illustrating how modern AI-assisted workflows can enable efficient development of practical real-time vision systems.
        image: /images/p3_1.png
        gallery:
          - url: /images/p3_1.png
          - url: /images/p3_2.png
        featured:
          name: "View Details"
          link: /posts/1/assignment-4/
        badges:
          - "Collision Avoidance"

      - title: Real-Time Kinematic Performance Evaluation of Mosaic-H GNSS Receiver on UAV Platforms Under Diverse Environmental Conditions
        content: "This paper presents a comprehensive evaluation of the Mosaic-H GNSS receiver's Real-Time Kinematic (RTK) performance when integrated with UAV platforms across diverse environments—including open-sky, urban canyon, and forested areas. Through systematic testing, the study achieved an 88.2% RTK fixed solution rate overall, with horizontal accuracy averaging 3.1 cm in optimal conditions. Key findings established critical operational thresholds: maintaining >10 m clearance from buildings to prevent multipath degradation, canopy coverage above 70% triggering float solutions, and speeds exceeding 8 m/s challenging phase tracking. The research introduced a novel Multipath Impact Score (MP Score) correlating environmental factors with positioning quality (R² = 0.87), and demonstrated that operating at altitudes of 20–25 m significantly improves fix stability and correction density. These results provide empirical benchmarks and operational guidelines for reliable centimeter-level UAV navigation in complex environments, with direct applications to precision agriculture, infrastructure inspection, and autonomous surveying."
        image: /images/Screenshot_2.png
        gallery:
          - url: /images/Screenshot_1.png
          - url: /images/Screenshot_2.png
        featured:
          name: "View Paper"
          link: https://www.cpgps.org/wwwroot/issue202401/JoGPS_2024_Joint_Issues_pp26-44.pdf
        badges:
          - "RTK GNSS"
          - "UAV Navigation"
            

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:odai7@buaa.edu.cn
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/odai357
      linkedin: https://www.linkedin.com/in/odai-othman-6699a9339/
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  caches:
    images:
      dir: :cacheDir/images

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
